### ISSUE TITLE
System.ArgumentException once moved to 4.7.1 from 4.2

### ISSUE THREAD

**Issue by cbrown11** [Particular/NServiceBus.Testing#15]
We are now getting the the errror message since upgrading to 4.7.1 and unsure why:

```
System.ArgumentException
Could not find a concrete type mapped to ###.Messages.Feed.Messages.IEnrichAndImportFeedDataCompleted
```
stack trace:
```
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.CreateInstance(Type t) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 414
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.CreateInstance[T]() in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 395
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.CreateInstance[T](Action`1 action) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 380
   at NServiceBus.Testing.StubBus.Reply[T](Action`1 messageConstructor) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Testing\StubBus.cs:line 237
```

We are using unobtrusive mode so establish the following at the start
```
MessageConventionExtensions.IsEventTypeAction = t => (t.Namespace != null 
&& t.Namespace.EndsWith(".Events"));
MessageConventionExtensions.IsCommandTypeAction = t => (t.Namespace != null 
&& t.Namespace.EndsWith(".Commands"));
MessageConventionExtensions.IsMessageTypeAction = t => (t.Namespace != null 
&& t.Namespace.EndsWith(".Messages"));
//  Also tried to include !t.Namespace.StartsWith("NServiceBus")
Test.Initialize();
```

Failing line in the handler
```
Bus.Reply<IEnrichAndImportFeedDataCompleted>(msg => msg.Successfull = summary.Successfull);
```

Message in question details
```
namespace ###.Messages.Feed.Messages
{
    public interface IEnrichAndImportFeedDataCompleted 
    {
        bool Successfull { get; set; }
    }
}
```
I've tried the workaround in https://github.com/Particular/NServiceBus.Testing/issues/9 but this doesn't resolve the issue. Though other orchestration unit tests are working fine.

Using NServiceBus 4.7.1 and Machine.Specifications 0.5.16

**Comment by johnsimons** [comment]
I cannot replicate this issue.
The following test passes:
```c#
    [TestFixture]
    public class Issue_15
    {
        [Test]
        public void SendMessageWithMultiIncomingHeaders()
        {
            Test.Initialize(config => config.Conventions()
                .DefiningCommandsAs(t => t == typeof(MyCommand))
                .DefiningMessagesAs(t => t == typeof(IEnrichAndImportFeedDataCompleted)));

            var command = new MyCommand();
            Test.Handler<MyCommandHandler>()
                .ExpectReply<IEnrichAndImportFeedDataCompleted>(m => m.Successfull)
                .OnMessage(command);
        }
    

        public class MyCommand
        {
        }

        public interface IEnrichAndImportFeedDataCompleted
        {
            bool Successfull { get; set; }
        }

        public class MyCommandHandler : IHandleMessages<MyCommand>
        {
            public IBus Bus { get; set; }

            public void Handle(MyCommand message)
            {
                Bus.Reply<IEnrichAndImportFeedDataCompleted>(m=> m.Successfull = true);
            }
        }
    }
```

**Comment by dmsergeev** [comment]
I am having the very same issue, but it only manifests itself when you run other NServiceBus handler tests with messages or events from a different assembly.
When run individually there's no exception.

**Comment by timbussmann** [comment]
@dmsergeev do you have a sample which reproduces your issue for us?

**Comment by dmsergeev** [comment]
@timbussmann not yet, but I have managed to reproduce it consistently. It seems like after you run `Test.Initialize` once supplying the assemblies to scan with `AssembliesToScan`  all subsequent calls to `AssembliesToScan` with different list of assemblies will have no effect on the registered assemblies. I will try to work out an example next week.

**Comment by cscorley** [comment]
Confirmed that we've been running into this same exception with the following packages:

```
  <package id="MSTest.TestAdapter" version="1.2.0" targetFramework="net45" />
  <package id="MSTest.TestFramework" version="1.2.0" targetFramework="net45" />
  <package id="NServiceBus" version="5.2.14" targetFramework="net45" />
  <package id="NServiceBus.Testing" version="5.2.0" targetFramework="net45" />
```

It seems to be whenever we have tests across two or more sets of MSTest `[TestClass]` with a `Test.Initialize` for each test.  Our fix was to only call `Test.Initialize` once, as suggested by @dmsergeev:

 ```csharp
    public static class NServiceBusTestLoader
    {
        private static bool _assembliesScanned = false;
        private static object _lockLoadAssemblies = new object();

        public static void LoadAssemblies()
        {
            lock (_lockLoadAssemblies)
            {
                if (!_assembliesScanned)
                {
                    _assembliesScanned = true;

                    Test.Initialize(config => config /* etc */);
                }
            }
        }
    }
```

We're calling the above from any test using the framework.

**Comment by timbussmann** [comment]
A sample which reproduces the issue would be definitely were helpful to look further into this.
Are you running tests in parallel?
Did you make sure that usages of `AssembliesToScan` contain the assembly containing the unobtrusive messages?
