### ISSUE TITLE
Assembly scanner and XUnit 2.0 does not work well together

### ISSUE THREAD

**Issue by janovesk** [Particular/NServiceBus.Testing#22]
From https://groups.google.com/forum/#!topic/particularsoftware/Q7O30xPUUko

NServiceBus.Testing
Version 4.7.5

XUnit 2.0 has moved the VS runner support to NuGet (as opposed to an extension).

I have a suite of tests that do Test.Initialize() and the scan now includes xunit.runner.visualstudio.testadapter.dll (as the NuGet package configures this to be copied to the output folder). The scan then looks (via dependency?) for Microsoft.VisualStudio.TestPlatform.ObjectModel which isn't found and so get a FileNotFoundException. 

I can just change to Test.Initialize(AllAssemblies.Except("xunit.runner.visualstudio.testadapter")) but I'm wondering if there is some other way I can do this via config for example? Or even add xunit to a known list of excludes for the Test.Initialize scan?

Thanks
Simon

/*
Email: simon.m.fox@gmail.com
Twitter: @simonmfox
*/

**Comment by danielmarbach** [comment]
I had a deeper look into this. Indeed I can reproduce the same exception.

````
Test Name:	XUnitReproBug.Class1.Fact
Test FullName:	XUnitReproBug.Class1.Fact
Test Source:	c:\particular\NServiceBus.Testing\src\XUnitReproBug\Class1.cs : line 10
Test Outcome:	Failed
Test Duration:	0:00:00.123

Result Message:	
System.Exception : Could not enumerate all types for 'C:\particular\NServiceBus.Testing\src\XUnitReproBug\bin\Debug\xunit.runner.visualstudio.testadapter.dll'.
Exceptions:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
Result StackTrace:	
at NServiceBus.Hosting.Helpers.AssemblyScanner.ScanAssembly(String assemblyPath, AssemblyScannerResults results) in c:\particular\NServiceBus\src\NServiceBus.Core\Hosting\Helpers\AssemblyScanner.cs:line 165
   at NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies() in c:\particular\NServiceBus\src\NServiceBus.Core\Hosting\Helpers\AssemblyScanner.cs:line 65
   at NServiceBus.BusConfiguration.GetAssembliesInDirectory(String path, String[] assembliesToSkip) in c:\particular\NServiceBus\src\NServiceBus.Core\BusConfiguration.cs:line 241
   at NServiceBus.BusConfiguration.ScanAssembliesInDirectory(String probeDirectory) in c:\particular\NServiceBus\src\NServiceBus.Core\BusConfiguration.cs:line 90
   at NServiceBus.BusConfiguration.BuildConfiguration() in c:\particular\NServiceBus\src\NServiceBus.Core\BusConfiguration.cs:line 182
   at NServiceBus.Bus.Create(BusConfiguration configuration) in c:\particular\NServiceBus\src\NServiceBus.Core\Bus.cs:line 17
   at NServiceBus.Testing.Test.Initialize(Action`1 customisations) in c:\particular\NServiceBus.Testing\src\NServiceBus.Testing\Test.cs:line 60
   at XUnitReproBug.Class1.Fact() in c:\particular\NServiceBus.Testing\src\XUnitReproBug\Class1.cs:line 11
```

I would argue it is not really a bug from the perspective of the library and also the core. By default all assemblies are scanned in the current directory. If an assembly cannot be loaded because a reference is missing then the scanning blows up and you have to manually exclude that library with `AllAssemblies.Except()`. 

So the workaround for the user is to do the following:

## Workaround
   Test.Initialize(c =>c.AssembliesToScan(AllAssemblies.Except("xunit.runner.visualstudio.testadapter")));

Now here comes the caveat. As soon as xunit2 is stable everyone using xunit2 in combination with the VS adapter will need to exclude the `"xunit.runner.visualstudio.testadapter` from the scanning. I have no idea how many users are affected. 

Here comes another catch:

I wanted to add a default exclusion. The issue is that exclusions are currently managed in the core. I think we don't want to upgrade/hotfix the core everytime we need to exclude something from the scanning. So ideally it should be possible to provide default exclusions in the Testing library. The issues is that currently we cannot do it properly. We expose the `BusConfiguration` in the lambda in the Initialize method BUT I cannot provide a default `AllAssemblies.Except` to `AssembliesToScan` because as soon as the user itself calls `AssembliesToScan` he overwrites all the defaults. The API of `AssembliesToScan` isn't intended to be called multiple times. 

What is the best way to move this forward?

// cc @andreasohlund @janovesk @johnsimons

**Comment by johnsimons** [comment]
Maybe concentrate on https://github.com/Particular/Requirements/issues/181 instead ?

**Comment by danielmarbach** [comment]
I'd say yes.

On Thu, Feb 19, 2015 at 12:51 AM, John Simons <notifications@github.com>
wrote:

> Maybe concentrate on Particular/Requirements#181
> <https://github.com/Particular/Requirements/issues/181> instead ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus.Testing/issues/22#issuecomment-74974303>
> .
>



-- 

Daniel Marbach

Solution Architect, Particular Software

Email:  daniel.marbach@particular.net

Web:    www.particular.net
<http://t.signauxneuf.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4RzDjlVS9QB88pTc_dW3Ljg7x56dWyBdgBXs402?t=http%3A%2F%2Fwww.particular.net%2F&si=4896787407044608&pi=33cc6202-1f31-4040-8d6c-e70641f44bba>

**Comment by janovesk** [comment]
This will be fixed by a better way of handling assembly scanning in a future version of NServiceBus. Use the exclusion workaround until then.

**Comment by brunobertechini** [comment]
Are this fixed in NServiceBus 5.2.12 / NServiceBus.Testing 5.1.1 ?

I am having the same issue.

Bruno

**Comment by timbussmann** [comment]
@brunobertechini not that I'm aware of. Please use the workaround suggested by @danielmarbach meanwhile.

@janovesk @johnsimons @danielmarbach should we exclude the dll from scanning by default for now?

**Comment by brunobertechini** [comment]
Ok Thanks

**Comment by timbussmann** [comment]
@brunobertechini btw. in case you're using ReSharper you can uninstall the `xunit.runner.visualstudio` plugin.
