### ISSUE TITLE
`AdvanceTime` throws exception when the same timeout is scheduled twice

### ISSUE THREAD

**Issue by saasen** [Particular/NServiceBus.Testing#512]
#### Description

When calling `AdvanceTime` on a saga where multiple timeouts of the same type is scheduled, it seems to crash.

Given the following test code:

```cs
var saga = new TestableSaga<MyCustomSaga, MyCustomSagaData>
{
    Data = new MyCustomSagaData
    {
        CustomerId = 12345
    }
});

await saga.Handle(new TrialStarted());
await saga.Handle(new TrialEnded());

var result = saga.AdvanceTime(SomeTimeBiggerThanDelay); // This line crashes
```

And given the following saga (with a lot of custom code omitted):

```cs
public class MyCustomSaga : Saga<MyCustomSagaData>,
    IAmStartedByMessages<TrialStarted>,
    IAmStartedByMessages<TrialEnded>
    IHandleTimeouts<MyCustomTimeout>
{
    protected override void ConfigureHowToFindSaga(SagaPropertyMapper<MyCustomSagaData> mapper)
    {
        mapper.ConfigureMapping<TrialStarted>(message => message.CustomerId)
            .ToSaga(sagaData => sagaData.CustomerId);
        mapper.ConfigureMapping<TrialEnded>(message => message.CustomerId)
            .ToSaga(sagaData => sagaData.CustomerId);
    }

    public Task Handle(TrialStarted message, IMessageHandlerContext context)
    {
        Data.TrialStarted = true;
        return RequestTimeout<MyCustomTimeout>(context,
            TimeSpan.FromHours(_options.Delay));
    }

    public Task Handle(TrialEnded message, IMessageHandlerContext context)
    {
        Data.TrialEnded = true;
        return RequestTimeout<MyCustomTimeout>(context,
            TimeSpan.FromHours(_options.Delay));
    }

    public async Task Timeout(MyCustomTimeout state, IMessageHandlerContext context)
    {
        MarkAsComplete();
    }
}
```

This throws an `Exception` with the following message: `No mapped value found from message, could not look up saga data.`. Is it because the saga is marked as complete in the first timeout handle? I would expect this not to crash, though.

#### Expected behavior

That you get two `HandleResult`s when calling `await saga.AdvanceTime(...)` (?)

#### Actual behavior

Throws `Exception` with the following message: `No mapped value found from message, could not look up saga data.`.

Stacktrace (custom code omitted):

```
System.Exception
No mapped value found from message, could not look up saga data.
   at NServiceBus.Testing.SagaMapper.GetMessageMappedValue(QueuedSagaMessage message) in /_/src/NServiceBus.Testing/Sagas/SagaMapper.cs:line 75
   at NServiceBus.Testing.TestableSaga`2.LoadSagaData(QueuedSagaMessage message, ISynchronizedStorageSession session, TestableMessageHandlerContext context) in /_/src/NServiceBus.Testing/Sagas/TestableSaga.cs:line 296
   at NServiceBus.Testing.TestableSaga`2.InnerHandle(QueuedSagaMessage message, String handleMethodName, TestableMessageHandlerContext context) in /_/src/NServiceBus.Testing/Sagas/TestableSaga.cs:line 216
   at NServiceBus.Testing.TestableSaga`2.HandleTimeout(OutgoingMessage`2 timeoutMessage, TestableMessageHandlerContext context) in /_/src/NServiceBus.Testing/Sagas/TestableSaga.cs:line 278
   at NServiceBus.Testing.TestableSaga`2.AdvanceTime(TimeSpan timeToAdvance, Func`2 provideContext, CancellationToken cancellationToken)
```

#### Versions

* `NServiceBus.Testing v8.0.1`
* `NServiceBus v8.0.3`

Please list the version of the relevant packages or applications in which the bug exists.        

### Steps to reproduce

Given the following test code:

```cs
var saga = new TestableSaga<MyCustomSaga, MyCustomSagaData>
{
    Data = new MyCustomSagaData
    {
        CustomerId = 12345
    }
});

await saga.Handle(new TrialStarted());
await saga.Handle(new TrialEnded());

var result = saga.AdvanceTime(SomeTimeBiggerThanDelay); // This line crashes
```

And given the following saga (with a lot of custom code omitted):

```cs
public class MyCustomSaga : Saga<MyCustomSagaData>,
    IAmStartedByMessages<TrialStarted>,
    IAmStartedByMessages<TrialEnded>
    IHandleTimeouts<MyCustomTimeout>
{
    protected override void ConfigureHowToFindSaga(SagaPropertyMapper<MyCustomSagaData> mapper)
    {
        mapper.ConfigureMapping<TrialStarted>(message => message.CustomerId)
            .ToSaga(sagaData => sagaData.CustomerId);
        mapper.ConfigureMapping<TrialEnded>(message => message.CustomerId)
            .ToSaga(sagaData => sagaData.CustomerId);
    }

    public Task Handle(TrialStarted message, IMessageHandlerContext context)
    {
        Data.TrialStarted = true;
        return RequestTimeout<MyCustomTimeout>(context,
            TimeSpan.FromHours(_options.Delay));
    }

    public Task Handle(TrialEnded message, IMessageHandlerContext context)
    {
        Data.TrialEnded = true;
        return RequestTimeout<MyCustomTimeout>(context,
            TimeSpan.FromHours(_options.Delay));
    }

    public async Task Timeout(MyCustomTimeout state, IMessageHandlerContext context)
    {
        MarkAsComplete();
    }
}
```

This throws an `Exception` with the following message: `No mapped value found from message, could not look up saga data.`. Is it because the saga is marked as complete in the first timeout handle? I would expect this not to crash, though.

**Comment by DavidBoike** [comment]
Great bug report, thank you!

You have a bit of an issue in your test code. You can't pre-set the saga data, and the messages you feed in would need to have the CustomerId set in order have that value read as the correlation id, but after I corrected those things, I got the same result as you.

The problem doesn't have anything to do with multiple timeouts of the same type.

Instead, the problem is that the testing framework doesn't deal with timeouts received **after** `MarkAsComplete()` is called.

So the first timeout arrives fine, and calls `MarkAsComplete()`, which removes the saga data from the fake internal saga storage.

Then the next timeout is processed, and it can't find the saga data any longer.

In NServiceBus, this missing data on a timeout would, I believe, write an output line about how a timeout was received for a saga that's long gone, but then that would be swallowed.

But in the saga testing framework, it currently shrugs off the fact that it can't find the saga by the SagaId contained in the timeout header and tries to load the saga data by a property value, and of course for a timeout, there's no mapping.

It's not enough to just return null here. We would need to modify the testing framework to properly emulate the "no big deal" behavior of NServiceBus and return the fact that the message is swallowed in the HandleResult so that can be asserted on.

Doing that might take a little more analysis than a common bugfix.

@saasen does that help to explain what's going on? Would you be looking to do an assertion on the second timeout being swallowed?

**Comment by saasen** [comment]
Thanks for the thorough explanation, @DavidBoike.

I didn't know I couldn't do that. I'll correct those mistakes. Since I don't know the internals of NServiceBus, I just guessed what might be wrong. 👍 

I thought about it might be the `MarkAsComplete()` call as well - I tried to step through the internals to see what might be wrong, but couldn't really understand everything beneath.

I understand that it might not be easy to fix this without analyzing it. Would a work around (even though not really feasible) be to catch and swallow that specific exception? This is somewhat of a rare case if I'm not mistaken.

> Would you be looking to do an assertion on the second timeout being swallowed?

Not that I know of. I guess it somehow could be handy? But to check if the timeout is correctly processing, I think it would be sufficient to assert the first timeout:

```cs
var result = saga.AdvanceTime(Time); // Expect one HandleResult here (and not fail), as the second timeout can't find the saga

result.First().Completed.Should().BeTrue();
result.First().FindSentMessage<MyCustomCommand>().Should().NotBeNull();
```

I don't know what kind of assertions you would do on the second timeout, since the saga isn't found, so nothing is done anyways. Maybe assert that it wasn't found? Not sure how useful that would be.

**Comment by DavidBoike** [comment]
@saasen Thanks for the feedback. That will help when we get to this.

Probably best for now would be to do like you said - advance time to between the 2 timeouts and assert on the first. If you wanted to then advance time again and assert that it throws an exception, I'd be sure to throw a comment on there that says "This may not throw in a future version of NServiceBus.Testing" or something like that.

**Comment by saasen** [comment]
@DavidBoike: I am unable to assert the first result, since the function throws an `Exception` and no result is returned. I don't know why I didn't think of that. 🤦‍♂️ 

Now I'm not sure how I can circumvent this issue.

**Comment by DavidBoike** [comment]
Is that because the timeouts are the same time, and you don’t advance time between placing them, so the timeouts are set to come due at the exact same moment?

**Comment by saasen** [comment]
Yeah, most likely. I could probably set an explicit time for the saga, so I can control the time to advance right in between.

**Comment by DavidBoike** [comment]
I fixed this in https://github.com/Particular/NServiceBus.Testing/pull/516 where any timeouts processed after `MarkAsComplete()` is called will simply be swallowed and will not result in an item in the results returned from AdvanceTime method. So in the case shown in this issue where 2 timeouts are set for the same time, the first one will have a result, the second one will be swallowed, and the array of results will contain only one item.

This will be released in version 8.1.0 within the next week or two.

**Comment by saasen** [comment]
Thanks for the quick fix, @DavidBoike! Looking forward to upgrading.

**Comment by DavidBoike** [comment]
@saasen this was just released in NServiceBus.Testing 8.1.0. [Release announcement here](https://discuss.particular.net/t/nservicebus-testing-8-1-0-minor-release-available/3625).
